version: '2'
services:

  api:
    container_name: challenge-microservice-api
    build: docker
    ports:
      - "3001:3000"
      - "3229:9229"
    env_file:
      - .env
    volumes:
      - .:/server
